export interface ThemeConfig {
  name: string;
  rootBg: string;
  textColor: string;
  textColorCode: string;
  cardBg: string;
  cardBorder: string;
  accentColor: string;
  accentText: string;
  accentBg: string;
  inputBg: string;
  inputBorder: string;
  buttonBg: string;
  buttonText: string;
  badgeBg: string;
  iconColor: string;
}

export const THEMES: Record<string, ThemeConfig> = {
  "Neon Cyan": {
    name: "Neon Cyan",
    rootBg: "bg-gradient-to-br from-[#08121A] via-[#0D1A25] to-[#04080D]",
    textColor: "text-[#F5FCFF]",
    textColorCode: "#F5FCFF",
    cardBg: "bg-white/5 backdrop-blur-md",
    cardBorder: "border-transparent",
    accentColor: "#00E5FF",
    accentText: "text-[#00E5FF]",
    accentBg: "bg-[#00E5FF]/20 text-[#00E5FF]",
    inputBg: "bg-black/20",
    inputBorder: "border-transparent",
    buttonBg: "bg-[#00E5FF]/25 text-[#00E5FF] font-bold",
    buttonText: "text-[#00E5FF]",
    badgeBg: "bg-black/30 text-[#00E5FF] border-transparent",
    iconColor: "#00E5FF",
  },
  "Light Neon Orange": {
    name: "Light Neon Orange",
    rootBg: "bg-gradient-to-br from-[#1A1208] via-[#20140C] to-[#0D0904]",
    textColor: "text-[#FFF8F0]",
    textColorCode: "#FFF8F0",
    cardBg: "bg-white/5 backdrop-blur-md",
    cardBorder: "border-transparent",
    accentColor: "#FFA726",
    accentText: "text-[#FFA726]",
    accentBg: "bg-[#FFA726]/20 text-[#FFA726] font-bold",
    inputBg: "bg-black/20",
    inputBorder: "border-transparent",
    buttonBg: "bg-[#FFA726]/25 text-[#FFA726] font-bold",
    buttonText: "text-[#FFA726]",
    badgeBg: "bg-black/30 text-[#FFD180] border-transparent",
    iconColor: "#FFA726",
  },
  "Classic Orange": {
    name: "Classic Orange",
    rootBg: "bg-gradient-to-br from-[#18120A] via-[#20160E] to-[#0B0804]",
    textColor: "text-[#FFF8F3]",
    textColorCode: "#FFF8F3",
    cardBg: "bg-white/5 backdrop-blur-md",
    cardBorder: "border-transparent",
    accentColor: "#FF6F00",
    accentText: "text-[#FF6F00]",
    accentBg: "bg-[#FF6F00]/20 text-[#FF6F00] font-bold",
    inputBg: "bg-black/20",
    inputBorder: "border-transparent",
    buttonBg: "bg-[#FF6F00]/25 text-white font-bold",
    buttonText: "text-[#FF6F00]",
    badgeBg: "bg-black/30 text-[#FFA000] border-transparent",
    iconColor: "#FF6F00",
  },
  "Neon Green": {
    name: "Neon Green",
    rootBg: "bg-gradient-to-br from-[#071208] via-[#0C140D] to-[#030804]",
    textColor: "text-[#F4FFF4]",
    textColorCode: "#F4FFF4",
    cardBg: "bg-white/5 backdrop-blur-md",
    cardBorder: "border-transparent",
    accentColor: "#39FF14",
    accentText: "text-[#39FF14]",
    accentBg: "bg-[#39FF14]/20 text-black font-bold",
    inputBg: "bg-black/20",
    inputBorder: "border-transparent",
    buttonBg: "bg-[#39FF14]/25 text-black font-bold",
    buttonText: "text-[#39FF14]",
    badgeBg: "bg-black/30 text-[#A5FF7A] border-transparent",
    iconColor: "#39FF14",
  },
  "Dark Professional": {
    name: "Dark Professional",
    rootBg: "bg-gradient-to-br from-[#0B0D10] via-[#101419] to-[#050608]",
    textColor: "text-[#FFFFFF]",
    textColorCode: "#FFFFFF",
    cardBg: "bg-white/5 backdrop-blur-md",
    cardBorder: "border-transparent",
    accentColor: "#4D8DFF",
    accentText: "text-[#4D8DFF]",
    accentBg: "bg-[#4D8DFF]/20 text-black font-bold",
    inputBg: "bg-black/20",
    inputBorder: "border-transparent",
    buttonBg: "bg-[#4D8DFF]/25 text-black font-bold",
    buttonText: "text-[#4D8DFF]",
    badgeBg: "bg-black/30 text-[#7FB2FF] border-transparent",
    iconColor: "#4D8DFF",
  },
  "Slate Grey": {
    name: "Slate Grey",
    rootBg: "bg-gradient-to-br from-[#17191D] via-[#1C2025] to-[#0E0F11]",
    textColor: "text-[#F7F7F7]",
    textColorCode: "#F7F7F7",
    cardBg: "bg-white/5 backdrop-blur-md",
    cardBorder: "border-transparent",
    accentColor: "#90A4AE",
    accentText: "text-[#90A4AE]",
    accentBg: "bg-[#90A4AE]/20 text-black font-bold",
    inputBg: "bg-black/20",
    inputBorder: "border-transparent",
    buttonBg: "bg-[#90A4AE]/25 text-black font-bold",
    buttonText: "text-[#90A4AE]",
    badgeBg: "bg-black/30 text-[#CFD8DC] border-transparent",
    iconColor: "#90A4AE",
  },
  "Pure Light": {
    name: "Pure Light",
    rootBg: "bg-gradient-to-br from-[#F5F7FA] via-white to-blue-50",
    textColor: "text-black font-bold",
    textColorCode: "#000000",
    cardBg: "bg-white/40 backdrop-blur-md",
    cardBorder: "border-transparent",
    accentColor: "#000000",
    accentText: "text-black font-black",
    accentBg: "bg-black/10 text-black font-bold",
    inputBg: "bg-black/5 text-black font-bold",
    inputBorder: "border-transparent",
    buttonBg: "bg-black/20 text-black font-bold",
    buttonText: "text-black font-bold",
    badgeBg: "bg-black/15 text-black border-transparent",
    iconColor: "#000000",
  },
  "Neon Red": {
    name: "Neon Red",
    rootBg: "bg-gradient-to-br from-[#17090C] via-[#1B0D10] to-[#0A0305]",
    textColor: "text-[#FFF5F6]",
    textColorCode: "#FFF5F6",
    cardBg: "bg-white/5 backdrop-blur-md",
    cardBorder: "border-transparent",
    accentColor: "#FF1744",
    accentText: "text-[#FF1744]",
    accentBg: "bg-[#FF1744]/20 text-white font-bold",
    inputBg: "bg-black/20",
    inputBorder: "border-transparent",
    buttonBg: "bg-[#FF1744]/25 text-white font-bold",
    buttonText: "text-[#FF1744]",
    badgeBg: "bg-black/30 text-[#FF5A7A] border-transparent",
    iconColor: "#FF1744",
  },
  "Royal Purple": {
    name: "Royal Purple",
    rootBg: "bg-gradient-to-br from-[#0F0918] via-[#151020] to-[#07040B]",
    textColor: "text-[#F7F5FF]",
    textColorCode: "#F7F5FF",
    cardBg: "bg-white/5 backdrop-blur-md",
    cardBorder: "border-transparent",
    accentColor: "#8E44FF",
    accentText: "text-[#8E44FF]",
    accentBg: "bg-[#8E44FF]/20 text-white font-bold",
    inputBg: "bg-black/20",
    inputBorder: "border-transparent",
    buttonBg: "bg-[#8E44FF]/25 text-white font-bold",
    buttonText: "text-[#8E44FF]",
    badgeBg: "bg-black/30 text-[#C08CFF] border-transparent",
    iconColor: "#8E44FF",
  },
  "Electric Blue": {
    name: "Electric Blue",
    rootBg: "bg-gradient-to-br from-[#08121E] via-[#0D1722] to-[#03060A]",
    textColor: "text-[#F8FBFF]",
    textColorCode: "#F8FBFF",
    cardBg: "bg-white/5 backdrop-blur-md",
    cardBorder: "border-transparent",
    accentColor: "#2979FF",
    accentText: "text-[#2979FF]",
    accentBg: "bg-[#2979FF]/20 text-white font-bold",
    inputBg: "bg-black/20",
    inputBorder: "border-transparent",
    buttonBg: "bg-[#2979FF]/25 text-white font-bold",
    buttonText: "text-[#2979FF]",
    badgeBg: "bg-black/30 text-[#82B1FF] border-transparent",
    iconColor: "#2979FF",
  }
};

export const getThemeConfig = (themeName: string): ThemeConfig => {
  return THEMES[themeName] || THEMES["Neon Cyan"];
};
